name: Build and Test

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:

  build:
    strategy:
      # run all tests even if e.g. image tests fail early
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - 3.11.0
        - '3.12'
        - '3.13'
        - '3.14'
        # Test all on ubuntu, test ends on macos and windows
        include:
        - os: macos-latest
          python-version: 3.11.0
        - os: windows-latest
          python-version: 3.11.0
        - os: macos-latest
          python-version: '3.14'
        - os: windows-latest
          python-version: '3.14'
        - os: ubuntu-22.04
          python-version: 3.11.0
          install-args: --resolution=lowest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        # 3.11.0 is not available through setup-uv
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        prune-cache: false

    - name: Build
      run: |
        uv sync --group test ${{ matrix.install-args }}
    - name: Run test suite
      run: |
        uv run --no-sync pytest --color yes
